services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://root:root@mongo:27017/sumo_traffic?authSource=admin
      - DISPLAY=host.docker.internal:0  # Relie au serveur X11 de l'hôte
    depends_on:
      - mongo
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Permet d'accéder à l'hôte depuis le conteneur
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=sumo_traffic
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: