# Utiliser une image officielle Node.js
FROM node:20

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer les dépendances
RUN npm install --omit=dev

# Copier le reste du code dans le conteneur
COPY . .

# Exposer le port (à ajuster selon ton app)
EXPOSE 3000

# Démarrer l'application
CMD ["node", "server.js"]
